package backend.gameplay;

enum abstract GameplayPaths(String) from String to String
{
	var START = 'START';

	var FIRST_CHOICE = 'FIRST_CHOICE';

	var MEET_THE_ARMY = 'MEET_THE_ARMY';
	var MEET_THE_ARMY_INTERACTIVE = 'MEET_THE_ARMY_INTERACTIVE';
	var GIVE_CONFIRMATION = 'GIVE_CONFIRMATION';

	var KEYPAD_SCENE = 'KEYPAD_SCENE';
	var SNEAK_PAST_THE_ARMY_INTRO = 'SNEAK_PAST_THE_ARMY_INTRO';
	var SNEAK_PAST_THE_ARMY = 'SNEAK_PAST_THE_ARMY';
	var PREVENT_CONFIRMATION = 'PREVENT_CONFIRMATION';

	var BETRAYAL_PATH_INTRO = 'BETRAYAL_PATH_INTRO';

	var LOYALTY_PATH_INTRO = 'LOYALTY_PATH_INTRO';

	var ENDING_REMEMBERANCE = 'ENDING_REMEMBERANCE';
	var ENDING_ONE_WHO_TRIED = 'ENDING_ONE_WHO_TRIED';

	var FAKE_END = 'FAKE_END';
}
